/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.14/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
    kotlin("jvm") version "2.0.10" apply false
    kotlin("plugin.spring") version "1.9.25" apply false
    id("org.springframework.boot") version "3.5.5" apply false
    id("io.spring.dependency-management") version "1.1.7" apply false
    id("org.jlleitschuh.gradle.ktlint") version "12.1.1" apply false
}

rootProject.name = "2025-daw-leic51n-2025-leic51n-10"

include("host")
project(":host").projectDir = file("code/jvm/modules/host")

// The domain module
include("domain")
project(":domain").projectDir = file("code/jvm/modules/domain")

// The HTTP module, with the HTTP interface
include("http")
project(":http").projectDir = file("code/jvm/modules/http")

// The services module
include("services")
project(":services").projectDir = file("code/jvm/modules/services")

// The repository module, with the repository interfaces
include("repository")
project(":repository").projectDir = file("code/jvm/modules/repository")

// The repository-jdbi module, with the JDBC/JDBI based repository implementation
include("repository-jdbi")
project(":repository-jdbi").projectDir = file("code/jvm/modules/repository-jdbi")
